name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: roel
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build the Docker image
      run: docker build -f docker/hab_data_api/Dockerfile . --tag ghcr.io/roel/hab_data_api:latest

    - name: Push the Docker image
      run: docker push ghcr.io/roel/hab_data_api:latest