name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -f docker/hab_data_api/Dockerfile . --tag hab_data_api:latest
    - name: Push the Docker image
      run: docker push hab_data_api:latest